repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: autopep8-wrapper
    -   id: check-docstring-first
    -   id: check-yaml
    -   id: double-quote-string-fixer
    -   id: name-tests-test
    -   id: requirements-txt-fixer
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v1.2.0
    hooks:
    -   id: reorder-python-imports
-   repo: https://github.com/asottile/pyupgrade
    rev: v1.6.1
    hooks:
    -   id: pyupgrade
-   repo: https://github.com/asottile/add-trailing-comma
    rev: v0.7.0
    hooks:
    -   id: add-trailing-comma
