language: python
matrix:
    include:
        -   env: TOXENV=py27
            python: 2.7
        -   env: TOXENV=py36
            python: 3.6
        -   env: TOXENV=py37
            python: 3.7
            dist: xenial
install: pip install coveralls tox
script: tox
after_success: coveralls
cache:
    directories:
        - $HOME/.cache/pip
        - $HOME/.cache/pre-commit
