environment:
    global:
        TOXENV: py
    matrix:
        - PYTHON: 'C:\Python27'
        - PYTHON: 'C:\Python36'
        - PYTHON: 'C:\Python37'

install:
    - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
    - pip install tox virtualenv --upgrade

# Not a C# project
build: false

test_script: tox

after_test:
  - "%PYTHON%\\Scripts\\pip.exe install wheel"
  - "%PYTHON%\\python.exe setup.py bdist_wheel"
  - "%PYTHON%-x64\\Scripts\\pip.exe install wheel"
  - "%PYTHON%-x64\\python.exe setup.py bdist_wheel"

artifacts:
  - path: dist\*

cache:
  - '%LOCALAPPDATA%\pip\cache'
  - '%USERPROFILE%\.cache\pre-commit'
